"""Add uitleg to weetje

Revision ID: bb70a41807eb
Revises: 
Create Date: 2025-06-20 01:03:42.500436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb70a41807eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('behandeling', schema=None) as batch_op:
        batch_op.alter_column('Beheerder_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('weetje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uitleg', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weetje', schema=None) as batch_op:
        batch_op.drop_column('uitleg')

    with op.batch_alter_table('behandeling', schema=None) as batch_op:
        batch_op.alter_column('Beheerder_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
